default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:
  password:

development:
  <<: *default
  database: rails_auth_development

test:
  <<: *default
  database: rails_auth_test

production:
  <<: *default
  database: rails_auth_production
